### ISSUE TITLE
Miscopy of parameters on deploy

### ISSUE THREAD

**Issue by Blancowicz** [EasyCorp/easy-deploy-bundle#34]
Hi there, 

we're facing an strange behavior with the parameters.yml.dist and parameters.yml files when deployed.

Here's the content of the two files after the deploy:
parameters.yml.dist
```yaml
parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: symfony
    database_user: root
    database_password: ~
    mailer_transport: gmail
    mailer_host: null
    mailer_user: anemail@gmail.com
    mailer_password: thepassword

    fos_mailer_user: anemail@gmail.com

    # A secret key that's used to generate certain security-related tokens
    secret: ThisTokenIsNotSoSecretChangeIt

    # JWTAuthentication
    jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem' # ssh private key path
    jwt_public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'  # ssh public key path
    jwt_key_pass_phrase:  '31A2xYz77i'                               # ssh key pass phrase
    jwt_token_ttl:        3600

    # Delivery addreses for dev
    dev_delivery_address: ['example@domain.com']
```

resultant parameters.yml
```yaml
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    fos_mailer_user: anemail@gmail.com
    secret: ThisTokenIsNotSoSecretChangeIt
    jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    jwt_public_key_path: '%kernel.root_dir%/../var/jwt/public.pem'
    jwt_key_pass_phrase: 31A2xYz77i
    jwt_token_ttl: 3600
    dev_delivery_address:
        - example@domain.com
```

As you can see, the parameters related to mailer_ are written with the default values. The parameter fos_mailer_user has been created 'cause it was breaking the deploy, as the fos_user.from_email.address configuration value cannot be null.
